
CREATE TABLE ROLE(
ID_ROLE INT IDENTITY(1,1) PRIMARY KEY,
NAME_ROLE NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE ACCOUNT(
ID_ACCOUNT INT IDENTITY(1,1) PRIMARY KEY,
USERNAME VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
STATE BIT DEFAULT 1
)
GO
CREATE TABLE USERS(
ID_USER INT IDENTITY(1,1) PRIMARY KEY,
CODE_USER VARCHAR(50) NOT NULL,
FIRSTNAME NVARCHAR(50),
LASTNAME NVARCHAR(50),
SEX BIT ,
PHONE VARCHAR(20),
ID_ACCOUNT INT ,
ID_ROLE INT,
EMAIL VARCHAR(100),
AVATAR VARCHAR(200),
STATE BIT DEFAULT 1,
CONSTRAINT FK_ACC1 FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT),
CONSTRAINT FK_RO1 FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE)
)
GO
CREATE TABLE CITY(
ID_CITY INT IDENTITY(1,1) PRIMARY KEY,
CITY NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE TOWN(
ID_TOWN INT IDENTITY(1,1) PRIMARY KEY,
TOWN NVARCHAR(50) NOT NULL,
ID_CITY INT,
CONSTRAINT FK_CI1 FOREIGN KEY (ID_CITY) REFERENCES CITY(ID_CITY),
CONSTRAINT UNI_CI1 UNIQUE(TOWN,ID_CITY)
)
GO
CREATE TABLE TOUR_GUIDE(
ID_TOURGUIDE INT IDENTITY(1,1) PRIMARY KEY,
TOURGUIDE INT DEFAULT 2,
DOB VARCHAR(50),
INDENTITY_CARD VARCHAR(50) UNIQUE,
ID_TOWN INT,
ADDRESS NVARCHAR(255),
PROMOTION NVARCHAR(255),
VIDEO_LINK VARCHAR(200),
REPULATION INT,
CONSTRAINT FK_USER1 FOREIGN KEY (TOURGUIDE) REFERENCES USERS(ID_USER),
CONSTRAINT FK_TOWN1 FOREIGN KEY (ID_TOWN) REFERENCES TOWN(ID_TOWN)
)
GO
CREATE TABLE TOURIST (
ID_TOURIST INT IDENTITY(1,1) PRIMARY KEY,
TOURIST INT DEFAULT 3,
PLACE_FROM NVARCHAR(255),
NATIONALITY NVARCHAR(50),
CONSTRAINT FK_USER2 FOREIGN KEY (TOURIST) REFERENCES USERS(ID_USER)
)
GO
CREATE TABLE BANK_CARD(
ID_BANKCARD INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY_CARD VARCHAR(20) NOT NULL,
NAME_BANK NVARCHAR(50),
NUMBER_CARD VARCHAR(30) NOT NULL,
ID_USER INT,
CONSTRAINT FK_USER4 FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
)
GO
CREATE TABLE TOUR(
ID_TOUR INT IDENTITY(1,1) PRIMARY KEY,
CODE_TOUR VARCHAR(20) NOT NULL,
NAME_TOUR NVARCHAR(50) NOT NULL,
ID_TOURGUIDE INT,
ID_CITY INT,
PRICE FLOAT,
CONSTRAINT FK_GUIDE FOREIGN KEY (ID_TOURGUIDE) REFERENCES TOUR_GUIDE(ID_TOURGUIDE),
CONSTRAINT FK_CI2 FOREIGN KEY (ID_CITY) REFERENCES CITY(ID_CITY)
)
GO
CREATE TABLE TIMES(
ID_TIME INT IDENTITY(1,1) PRIMARY KEY,
TIME_START VARCHAR(50) NOT NULL,
TIME_END VARCHAR(50) ,
ID_TOUR INT,
CONSTRAINT FK_TOUR1 FOREIGN KEY (ID_TOUR) REFERENCES TOUR(ID_TOUR)
)
GO
CREATE TABLE PLACE_VISIT(
ID_PLACE INT IDENTITY(1,1) PRIMARY KEY,
NAME_PLACE NVARCHAR(50) NOT NULL,
ID_TIME INT,
ID_TOWN INT,
ADDRESS NVARCHAR(255),
DESCRIBLE NVARCHAR(255),
CONSTRAINT FK_TIME FOREIGN KEY (ID_TIME) REFERENCES TIMES(ID_TIME),
CONSTRAINT FK_TOWN2 FOREIGN KEY (ID_TOWN) REFERENCES TOWN(ID_TOWN)
)
GO
CREATE TABLE BOOK_TOUR(
ID_BOOKTOUR INT IDENTITY(1,1) PRIMARY KEY,
ID_TOUR INT,
ID_TOURIST INT,
COST FLOAT,
STATUS INT DEFAULT 3,
STATE INT DEFAULT 2,
PAYMENT_STATUS INT,
CONSTRAINT FK_TOUR2 FOREIGN KEY (ID_TOUR) REFERENCES TOUR(ID_TOUR),
CONSTRAINT FK_TOURIST2 FOREIGN KEY (ID_TOURIST) REFERENCES TOURIST(ID_TOURIST)
)
GO
CREATE TABLE PAYMENT(
ID_PAYMENT INT IDENTITY(1,1) PRIMARY KEY,
ID_BOOKTOUR INT,
AMOUNT FLOAT,
CONSTRAINT FK_BT1 FOREIGN KEY (ID_BOOKTOUR) REFERENCES BOOK_TOUR(ID_BOOKTOUR)
)
GO
CREATE TABLE FEEDBACK(
ID_FEEDBACK INT IDENTITY(1,1) PRIMARY KEY,
ID_BOOKTOUR INT,
ID_USER_SEND INT,
TITLE NVARCHAR(50) ,
CONTENT NVARCHAR(255) ,
STATUS INT,
CONSTRAINT FK_BT2 FOREIGN KEY (ID_BOOKTOUR) REFERENCES BOOK_TOUR(ID_BOOKTOUR),
CONSTRAINT FK_USER3 FOREIGN KEY (ID_USER_SEND) REFERENCES TOURIST(ID_TOURIST)
)
GO